spring.application.name=DigitalGoldWallet

# ----- Database -----
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ----- JPA / Hibernate -----
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ----- Server -----
server.port=${PORT:8080}

# ----- JWT -----
jwt.secret=${JWT_SECRET}

# ----- Swagger / OpenAPI -----
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ----- Disable Eureka -----
eureka.client.enabled=false
spring.cloud.discovery.enabled=false